<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all"/>
      <PackageReference Include="MudBlazor"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\data\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\data\sql\Top2000.Data.ClientDatabase\Top2000.Data.ClientDatabase.csproj" />
      <ProjectReference Include="..\..\features\Top2000.Features.Json\Top2000.Features.Json.csproj" />
      <ProjectReference Include="..\..\features\Top2000.Features\Top2000.Features.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="wwwroot\data\1999.json" />
      <EmbeddedResource Include="wwwroot\data\1999.json" />
      <Content Remove="wwwroot\data\2000.json" />
      <EmbeddedResource Include="wwwroot\data\2000.json" />
      <Content Remove="wwwroot\data\2001.json" />
      <EmbeddedResource Include="wwwroot\data\2001.json" />
      <Content Remove="wwwroot\data\2002.json" />
      <EmbeddedResource Include="wwwroot\data\2002.json" />
      <Content Remove="wwwroot\data\2003.json" />
      <EmbeddedResource Include="wwwroot\data\2003.json" />
      <Content Remove="wwwroot\data\2004.json" />
      <EmbeddedResource Include="wwwroot\data\2004.json" />
      <Content Remove="wwwroot\data\2005.json" />
      <EmbeddedResource Include="wwwroot\data\2005.json" />
      <Content Remove="wwwroot\data\2006.json" />
      <EmbeddedResource Include="wwwroot\data\2006.json" />
      <Content Remove="wwwroot\data\2007.json" />
      <EmbeddedResource Include="wwwroot\data\2007.json" />
      <Content Remove="wwwroot\data\2008.json" />
      <EmbeddedResource Include="wwwroot\data\2008.json" />
      <Content Remove="wwwroot\data\2009.json" />
      <EmbeddedResource Include="wwwroot\data\2009.json" />
      <Content Remove="wwwroot\data\2010.json" />
      <EmbeddedResource Include="wwwroot\data\2010.json" />
      <Content Remove="wwwroot\data\2011.json" />
      <EmbeddedResource Include="wwwroot\data\2011.json" />
      <Content Remove="wwwroot\data\2012.json" />
      <EmbeddedResource Include="wwwroot\data\2012.json" />
      <Content Remove="wwwroot\data\2013.json" />
      <EmbeddedResource Include="wwwroot\data\2013.json" />
      <Content Remove="wwwroot\data\2014.json" />
      <EmbeddedResource Include="wwwroot\data\2014.json" />
      <Content Remove="wwwroot\data\2015.json" />
      <EmbeddedResource Include="wwwroot\data\2015.json" />
      <Content Remove="wwwroot\data\2016.json" />
      <EmbeddedResource Include="wwwroot\data\2016.json" />
      <Content Remove="wwwroot\data\2017.json" />
      <EmbeddedResource Include="wwwroot\data\2017.json" />
      <Content Remove="wwwroot\data\2018.json" />
      <EmbeddedResource Include="wwwroot\data\2018.json" />
      <Content Remove="wwwroot\data\2019.json" />
      <EmbeddedResource Include="wwwroot\data\2019.json" />
      <Content Remove="wwwroot\data\2020.json" />
      <EmbeddedResource Include="wwwroot\data\2020.json" />
      <Content Remove="wwwroot\data\2021.json" />
      <EmbeddedResource Include="wwwroot\data\2021.json" />
      <Content Remove="wwwroot\data\2022.json" />
      <EmbeddedResource Include="wwwroot\data\2022.json" />
      <Content Remove="wwwroot\data\2023.json" />
      <EmbeddedResource Include="wwwroot\data\2023.json" />
      <Content Remove="wwwroot\data\2024.json" />
      <EmbeddedResource Include="wwwroot\data\2024.json" />
      <Content Remove="wwwroot\data\2025.json" />
      <EmbeddedResource Include="wwwroot\data\2025.json" />
      <Content Remove="wwwroot\data\version.json" />
      <EmbeddedResource Include="wwwroot\data\version.json" />
    </ItemGroup>

</Project>
