<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ImplicitUsings>enable</ImplicitUsings>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Controls\" />
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\data\sql\Top2000.Data.ClientDatabase\Top2000.Data.ClientDatabase.csproj" />
      <ProjectReference Include="..\src\features\sql\Top2000.Features.SQLite\Top2000.Features.SQLite.csproj" />
    </ItemGroup>

    <ItemGroup>
      <MauiFont Include="Assets\Fonts\MaterialIcons.ttf" />
      <MauiFont Include="Assets\Fonts\OpenSans-Regular.ttf" />
      <MauiFont Include="Assets\Fonts\OpenSans-Semibold.ttf" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Mono.Android">
        <HintPath>..\..\..\..\.dotnet\packs\Microsoft.Android.Ref.36\36.1.2\ref\net10.0\Mono.Android.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
